### ISSUE TITLE
Question about trees used here

### ISSUE THREAD

**Issue by cahuparo** [slt666666/Phylogenetic_distance_plot#1]
Hi Toshiyuki,

Hope all is well. I was wondering how did you generated the input trees here. 

A) did you build a combined tree for all species NBARCs and them pruned all non-arabidopsis tips from a copied tree?

Or 

B) did you made two trees one with all including arabidopsis and one with only arabidopsis? 

I am wondering if doing B one could get a different tree and distances for arabidopsis. I am trying to use this analysis to calculate distance within the same species NBARCs. Something like: 

All tree = 6X I. batatas cultivars NBARCs + 2X I. trifida NBARCs.

Only Itf tree = 2X I. trifida NBARCs.

But I want to make sure I used the "right" trees.

Best,

Camilo

**Comment by slt666666** [comment]
Hi Camilo,
Sorry for the late response.

In my case, I performed (A) because I'd like to keep the order of Arabidopsis NLRs.
So I just made a combined tree.

I hope it helps.
Best,
Toshi

**Comment by cahuparo** [comment]
Hi Toshi,

That's what I ended up doing and it works well. Thanks for replying though. 

Best,

Camilo
